import { LocalizedText } from "../../../shared/i18n/LocalizedText";
import { createAdaptiveStyleSheet } from "../../../shared/theme/adaptiveStyles";
import { Ionicons } from "@expo/vector-icons";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import type { AdminStackParamList } from "../../../app/navigation/navigation.types";
import { colors, shadows, typography } from "../../../shared/theme";
import { AdminHeader } from "../components/AdminHeader";

const days = [{ label: "س", value: 36 }, { label: "ح", value: 52 }, { label: "ن", value: 43 }, { label: "ث", value: 68 }, { label: "ر", value: 56 }, { label: "خ", value: 84 }, { label: "ج", value: 72 }];
const transactions = [{ title: "عمولة صيانة #AM-2421", amount: "+18 ₪", time: "10:22 ص" }, { title: "اشتراك Pro • طارق", amount: "+49 ₪", time: "9:40 ص" }, { title: "استرداد طلب #AM-2412", amount: "-35 ₪", time: "أمس" }];

export function AdminFinanceScreen({ navigation }: NativeStackScreenProps<AdminStackParamList, "AdminFinance">) {
  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}><AdminHeader title="المالية والعمولات" subtitle="إيرادات المنصة والتسويات" onBack={() => navigation.goBack()} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><LocalizedText style={styles.heroLabel}>صافي إيرادات هذا الشهر</LocalizedText><LocalizedText style={styles.heroValue}>38,420 ₪</LocalizedText><View style={styles.heroTrend}><Ionicons name="trending-up" size={14} color="#6EE7B7" /><LocalizedText style={styles.heroTrendText}>+12.8% عن الشهر الماضي</LocalizedText></View></View>
    <View style={styles.metrics}><Metric label="عمولات اليوم" value="1,480 ₪" /><Metric label="اشتراكات Pro" value="3,332 ₪" /><Metric label="بانتظار التسوية" value="820 ₪" /></View>
    <View style={styles.card}><View style={styles.cardTop}><LocalizedText style={styles.cardTitle}>نشاط آخر 7 أيام</LocalizedText><LocalizedText style={styles.cardHint}>بالشيكل</LocalizedText></View><View style={styles.chart}>{days.map((day) => <View key={day.label} style={styles.barWrap}><View style={[styles.bar, { height: day.value }]} /><LocalizedText style={styles.day}>{day.label}</LocalizedText></View>)}</View></View>
    <View style={styles.card}><LocalizedText style={styles.cardTitle}>آخر الحركات المالية</LocalizedText>{transactions.map((item, index) => <View key={item.title} style={[styles.transaction, index === transactions.length - 1 && styles.last]}><View style={styles.transactionIcon}><Ionicons name={item.amount.startsWith("-") ? "arrow-undo" : "cash"} size={17} color={item.amount.startsWith("-") ? "#BE123C" : "#047857"} /></View><View style={styles.transactionCopy}><LocalizedText style={styles.transactionTitle}>{item.title}</LocalizedText><LocalizedText style={styles.time}>{item.time}</LocalizedText></View><LocalizedText style={[styles.amount, item.amount.startsWith("-") && styles.negative]}>{item.amount}</LocalizedText></View>)}</View>
    <Pressable onPress={() => Alert.alert("تقرير مالي", "تم تجهيز تقرير المالية بصيغة قابلة للتصدير.")} style={styles.primary}><Ionicons name="download" size={17} color={colors.text} /><LocalizedText style={styles.primaryText}>تصدير التقرير المالي</LocalizedText></Pressable>
  </ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><LocalizedText style={styles.metricLabel}>{label}</LocalizedText><LocalizedText style={styles.metricValue}>{value}</LocalizedText></View>; }
const styles = createAdaptiveStyleSheet({
  safe: { backgroundColor: "#F8F7F4", flex: 1 }, content: { gap: 11, padding: 14, paddingBottom: 30 }, hero: { ...shadows.raised, backgroundColor: colors.secondary, borderRadius: 21, padding: 17 }, heroLabel: { color: "#CBD5E1", fontFamily: typography.fontFamily, fontSize: 9, textAlign: "right" }, heroValue: { color: colors.primary, fontFamily: typography.fontFamily, fontSize: 29, fontWeight: "900", marginTop: 3, textAlign: "right" }, heroTrend: { alignItems: "center", flexDirection: "row-reverse", gap: 4, marginTop: 5 }, heroTrendText: { color: "#6EE7B7", fontFamily: typography.fontFamily, fontSize: 8 }, metrics: { flexDirection: "row-reverse", gap: 7 }, metric: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 13, borderWidth: 1, flex: 1, padding: 9 }, metricLabel: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 7, textAlign: "center" }, metricValue: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800", marginTop: 3, textAlign: "center" }, card: { ...shadows.subtle, backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 17, borderWidth: 1, padding: 12 }, cardTop: { flexDirection: "row-reverse", justifyContent: "space-between" }, cardTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 11, fontWeight: "800", textAlign: "right" }, cardHint: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7 }, chart: { alignItems: "flex-end", flexDirection: "row-reverse", gap: 10, height: 110, justifyContent: "space-around", marginTop: 10 }, barWrap: { alignItems: "center", flex: 1, justifyContent: "flex-end" }, bar: { backgroundColor: colors.primary, borderRadius: 5, minHeight: 12, width: 16 }, day: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 7, marginTop: 5 }, transaction: { alignItems: "center", borderBottomColor: "#F0ECE3", borderBottomWidth: 1, flexDirection: "row-reverse", gap: 8, minHeight: 59 }, last: { borderBottomWidth: 0 }, transactionIcon: { alignItems: "center", backgroundColor: "#F8F7F4", borderRadius: 10, height: 35, justifyContent: "center", width: 35 }, transactionCopy: { flex: 1 }, transactionTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 9, fontWeight: "700", textAlign: "right" }, time: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7, marginTop: 2, textAlign: "right" }, amount: { color: "#047857", fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800" }, negative: { color: "#BE123C" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 14, flexDirection: "row-reverse", gap: 6, justifyContent: "center", minHeight: 49 }, primaryText: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800" }
});
