import { LocalizedText } from "../../../shared/i18n/LocalizedText";
import { createAdaptiveStyleSheet } from "../../../shared/theme/adaptiveStyles";
import { Ionicons } from "@expo/vector-icons";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useEffect, useState } from "react";
import { SafeAreaView } from "react-native-safe-area-context";

import type { AdminStackParamList } from "../../../app/navigation/navigation.types";
import { colors, shadows, typography } from "../../../shared/theme";
import { AdminHeader } from "../components/AdminHeader";
import { adminApi } from "../../../services/api/adminApi";
import { appConfig } from "../../../app/config/appConfig";

export function AdminFinanceScreen({ navigation }: NativeStackScreenProps<AdminStackParamList, "AdminFinance">) {
  const [summary, setSummary] = useState<Record<string, unknown>>();
  const [failed, setFailed] = useState(false);
  useEffect(() => { if (appConfig.demoMode) return; let active = true; void adminApi.summary().then((value) => { if (active) setSummary(value); }).catch(() => { if (active) setFailed(true); }); return () => { active = false; }; }, []);
  const commissions = summary?.commissions && typeof summary.commissions === "object" ? summary.commissions as Record<string, unknown> : {};
  const amount = (value: unknown) => typeof value === "number" ? `${value.toLocaleString()} ₪` : "—";
  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}><AdminHeader title="المالية والعمولات" subtitle="إيرادات المنصة والتسويات" onBack={() => navigation.goBack()} /><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.hero}><LocalizedText style={styles.heroLabel}>إجمالي عمولات المنصة المسجلة</LocalizedText><LocalizedText style={styles.heroValue}>{amount(commissions.platformFees)}</LocalizedText><LocalizedText style={styles.heroTrendText}>{failed ? "تعذر تحميل ملخص المالية" : "القيمة الإجمالية المحسوبة من سجلات الأعمال المكتملة"}</LocalizedText></View>
    <View style={styles.metrics}><Metric label="إجمالي الأعمال" value={amount(commissions.gross)} /><Metric label="أعمال مالية مسجلة" value={typeof commissions.jobs === "number" ? String(commissions.jobs) : "—"} /><Metric label="مشتركو Pro النشطون" value={typeof summary?.proSubscribers === "number" ? String(summary.proSubscribers) : "—"} /></View>
    <View style={styles.card}><LocalizedText style={styles.cardTitle}>ملخص المنصة</LocalizedText><LocalizedText style={styles.transactionTitle}>عدد الأعمال المكتملة: {typeof summary?.completedJobs === "number" ? summary.completedJobs : "—"}</LocalizedText><LocalizedText style={styles.time}>لا توفر الخدمة حالياً تقارير يومية أو قائمة حركات مالية مفصلة.</LocalizedText></View>
  </ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><LocalizedText style={styles.metricLabel}>{label}</LocalizedText><LocalizedText style={styles.metricValue}>{value}</LocalizedText></View>; }
const styles = createAdaptiveStyleSheet({
  safe: { backgroundColor: "#F8F7F4", flex: 1 }, content: { gap: 11, padding: 14, paddingBottom: 30 }, hero: { ...shadows.raised, backgroundColor: colors.secondary, borderRadius: 21, padding: 17 }, heroLabel: { color: "#CBD5E1", fontFamily: typography.fontFamily, fontSize: 9, textAlign: "right" }, heroValue: { color: colors.primary, fontFamily: typography.fontFamily, fontSize: 29, fontWeight: "900", marginTop: 3, textAlign: "right" }, heroTrend: { alignItems: "center", flexDirection: "row-reverse", gap: 4, marginTop: 5 }, heroTrendText: { color: "#6EE7B7", fontFamily: typography.fontFamily, fontSize: 8 }, metrics: { flexDirection: "row-reverse", gap: 7 }, metric: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 13, borderWidth: 1, flex: 1, padding: 9 }, metricLabel: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 7, textAlign: "center" }, metricValue: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800", marginTop: 3, textAlign: "center" }, card: { ...shadows.subtle, backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 17, borderWidth: 1, padding: 12 }, cardTop: { flexDirection: "row-reverse", justifyContent: "space-between" }, cardTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 11, fontWeight: "800", textAlign: "right" }, cardHint: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7 }, chart: { alignItems: "flex-end", flexDirection: "row-reverse", gap: 10, height: 110, justifyContent: "space-around", marginTop: 10 }, barWrap: { alignItems: "center", flex: 1, justifyContent: "flex-end" }, bar: { backgroundColor: colors.primary, borderRadius: 5, minHeight: 12, width: 16 }, day: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 7, marginTop: 5 }, transaction: { alignItems: "center", borderBottomColor: "#F0ECE3", borderBottomWidth: 1, flexDirection: "row-reverse", gap: 8, minHeight: 59 }, last: { borderBottomWidth: 0 }, transactionIcon: { alignItems: "center", backgroundColor: "#F8F7F4", borderRadius: 10, height: 35, justifyContent: "center", width: 35 }, transactionCopy: { flex: 1 }, transactionTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 9, fontWeight: "700", textAlign: "right" }, time: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7, marginTop: 2, textAlign: "right" }, amount: { color: "#047857", fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800" }, negative: { color: "#BE123C" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 14, flexDirection: "row-reverse", gap: 6, justifyContent: "center", minHeight: 49 }, primaryText: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800" }
});
