import { LocalizedTextInput } from "../../../shared/i18n/LocalizedTextInput";
import { LocalizedText } from "../../../shared/i18n/LocalizedText";
import { createAdaptiveStyleSheet } from "../../../shared/theme/adaptiveStyles";
import { Ionicons } from "@expo/vector-icons";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { useMemo, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import type { AdminStackParamList } from "../../../app/navigation/navigation.types";
import { colors, shadows, typography } from "../../../shared/theme";
import { platformUsers } from "../adminData";
import { AdminHeader } from "../components/AdminHeader";

export function AdminUsersScreen({ navigation }: NativeStackScreenProps<AdminStackParamList, "AdminUsers">) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"all" | "technician" | "customer">("all");
  const users = useMemo(() => platformUsers.filter((user) => (!query || `${user.name} ${user.role}`.includes(query)) && (filter === "all" || (filter === "technician" ? user.role.includes("فني") : user.role === "عميل"))), [query, filter]);
  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}><AdminHeader title="المستخدمون والفنيون" subtitle="إدارة الحسابات وحالة النشاط" onBack={() => navigation.goBack()} /><View style={styles.search}><Ionicons name="search" size={17} color="#94A3B8" /><LocalizedTextInput value={query} onChangeText={setQuery} placeholder="ابحث بالاسم أو نوع الحساب" placeholderTextColor="#94A3B8" style={styles.input} /></View><View style={styles.filters}>{(["all", "technician", "customer"] as const).map((item) => <Pressable key={item} onPress={() => setFilter(item)} style={[styles.filter, filter === item && styles.activeFilter]}><LocalizedText style={[styles.filterText, filter === item && styles.activeText]}>{item === "all" ? "الكل" : item === "technician" ? "الفنيون" : "العملاء"}</LocalizedText></Pressable>)}</View><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
    <View style={styles.metrics}><Metric label="كل المستخدمين" value="1,284" /><Metric label="فنيون موثقون" value="312" /><Metric label="نشطون اليوم" value="486" /></View>
    {users.map((user) => <Pressable key={user.id} onPress={() => Alert.alert(user.name, `${user.role}\n${user.status}\n${user.jobs} طلب/عمل مسجل`)} style={({ pressed }) => [styles.user, pressed && styles.pressed]}><View style={styles.avatar}><LocalizedText style={styles.avatarText}>{user.name.charAt(0)}</LocalizedText><View style={[styles.statusDot, user.tone === "danger" ? styles.danger : user.tone === "warning" ? styles.warning : styles.success]} /></View><View style={styles.copy}><LocalizedText style={styles.name}>{user.name}</LocalizedText><LocalizedText style={styles.role}>{user.role} • {user.jobs} عملية</LocalizedText></View><View style={[styles.badge, user.tone === "danger" ? styles.dangerBg : user.tone === "warning" ? styles.warningBg : styles.successBg]}><LocalizedText style={[styles.badgeText, user.tone === "danger" ? styles.dangerText : user.tone === "warning" ? styles.warningText : styles.successText]}>{user.status}</LocalizedText></View><Ionicons name="chevron-back" size={15} color="#94A3B8" /></Pressable>)}
  </ScrollView></SafeAreaView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><LocalizedText style={styles.metricLabel}>{label}</LocalizedText><LocalizedText style={styles.metricValue}>{value}</LocalizedText></View>; }
const styles = createAdaptiveStyleSheet({
  safe: { backgroundColor: "#F8F7F4", flex: 1 }, search: { alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 13, borderWidth: 1, flexDirection: "row-reverse", gap: 7, marginHorizontal: 14, marginTop: 11, paddingHorizontal: 10 }, input: { color: colors.text, flex: 1, fontFamily: typography.fontFamily, fontSize: 9, minHeight: 43, textAlign: "right" }, filters: { flexDirection: "row-reverse", gap: 6, paddingHorizontal: 14, paddingTop: 9 }, filter: { borderRadius: 9, paddingHorizontal: 12, paddingVertical: 7 }, activeFilter: { backgroundColor: colors.secondary }, filterText: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 8, fontWeight: "600" }, activeText: { color: "white" }, content: { gap: 9, padding: 14, paddingBottom: 30 }, metrics: { flexDirection: "row-reverse", gap: 7 }, metric: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 13, borderWidth: 1, flex: 1, padding: 9 }, metricLabel: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 7, textAlign: "center" }, metricValue: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 12, fontWeight: "800", marginTop: 2 }, user: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 16, borderWidth: 1, flexDirection: "row-reverse", gap: 9, minHeight: 72, padding: 10 }, pressed: { opacity: 0.72 }, avatar: { alignItems: "center", backgroundColor: colors.secondary, borderRadius: 21, height: 42, justifyContent: "center", position: "relative", width: 42 }, avatarText: { color: colors.primary, fontFamily: typography.fontFamily, fontSize: 16, fontWeight: "800" }, statusDot: { borderColor: "white", borderRadius: 6, borderWidth: 1.5, bottom: 0, height: 12, position: "absolute", right: 0, width: 12 }, success: { backgroundColor: "#10B981" }, warning: { backgroundColor: "#F59E0B" }, danger: { backgroundColor: "#E11D48" }, copy: { flex: 1 }, name: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800", textAlign: "right" }, role: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 7, marginTop: 3, textAlign: "right" }, badge: { borderRadius: 8, maxWidth: 84, paddingHorizontal: 6, paddingVertical: 5 }, badgeText: { fontFamily: typography.fontFamily, fontSize: 6, fontWeight: "700", textAlign: "center" }, successBg: { backgroundColor: "#ECFDF5" }, successText: { color: "#047857" }, warningBg: { backgroundColor: "#FEF3C7" }, warningText: { color: "#92400E" }, dangerBg: { backgroundColor: "#FFF1F2" }, dangerText: { color: "#BE123C" }
});
