const exact: Record<string, string> = {
  "إدارة المنصة": "Platform management", "إدارة الحساب": "Account management", "إعدادات الحساب": "Account settings", "إدارة بياناتك وخدماتك في عَمِّرها": "Manage your AMMERHA profile and services", "إدارة ملفك وخدماتك وأرباحك": "Manage your profile, services, and earnings",
  "حسابي": "My account", "حساب الفني": "Technician account", "طلباتي": "My requests", "أعمالي": "My work", "الرسائل": "Messages", "الإشعارات": "Notifications", "الخريطة والطلبات": "Map & requests", "مركز الإشعارات": "Notification center",
  "طلب صيانة": "Repair request", "تفاصيل طلب الصيانة": "Repair request details", "تفاصيل الطلب": "Request details", "ملخص طلب الصيانة": "Repair request summary", "ملخص طلبك": "Your request summary", "وصف المشكلة": "Problem description", "نوع الخدمة": "Service type", "موقع الصيانة بالقدس": "Service location in Jerusalem",
  "احكِ المشكلة بصوتك": "Describe the issue by voice", "احكِ المشكلة بصوتك أو صوّرها": "Describe the issue or take a photo", "أرفق صورة أو فيديو للعطل": "Attach a photo or video", "الصورة تساعد الذكاء الاصطناعي على تشخيص أدق": "A photo helps AI provide a more accurate diagnosis", "صوتك": "Your voice", "إعادة التسجيل": "Record again", "اعتماد النص": "Use this text",
  "التشخيص المبدئي": "Initial diagnosis", "التشخيص المبدئي يحتاج إلى تأكيد": "The initial diagnosis needs confirmation", "تحليل أولي للعطل": "Initial issue analysis", "الطلب قيد التحليل": "Analyzing request", "نحلّل المشكلة...": "Analyzing the issue...", "الذكاء الاصطناعي يشخّص العطل ويقترح السعر العادل فوراً": "AI diagnoses the issue and suggests a fair price instantly", "السعر العادل": "Fair price", "السعر العادل المتوقع": "Estimated fair price", "السعر العادل المقترح": "Suggested fair price", "تقدير إرشادي، وليس سعراً نهائياً مضموناً.": "An estimate, not a guaranteed final price.",
  "تعديل التفاصيل": "Edit details", "راجع البيانات قبل إرسالها للفنيين": "Review before sending to technicians", "تأكد من التفاصيل قبل إرسالها للفنيين القريبين منك.": "Review the details before sending to nearby technicians.", "تم تجهيز الطلب للانتقال إلى الصيانة.": "The request is ready for service.",
  "العروض المتاحة": "Available offers", "تفاصيل العرض": "Offer details", "تأكيد قبول العرض": "Confirm offer", "إرسال عرض": "Send offer", "إرسال عرض صيانة": "Send service offer", "إرسال العرض للعميل": "Send offer to customer", "قيمة العرض المالي": "Offer price", "رسالة العرض للعميل": "Offer message", "تم إرسال العرض للعميل": "Offer sent to customer", "إنشاء عرض يدوي وإرساله": "Create and send a manual offer",
  "مساعد العرض الذكي": "Smart offer assistant", "مساعد العروض الذكي": "Smart offer assistant", "اقتراح ذكي": "Smart suggestion", "رسالة العرض المقترحة": "Suggested offer message", "عرضك المقترح": "Your suggested offer", "السعر المقترح ضمن متوسط صيانة القدس": "Suggested price is within Jerusalem's service average", "الاقتراح مساعد لك. راجع التفاصيل والسعر قبل إرسال العرض للعميل.": "This suggestion assists you. Review the details and price before sending.",
  "المهمة النشطة": "Active job", "معلومات المهمة": "Job information", "تقدم المهمة": "Job progress", "مراحل العمل": "Work stages", "مراحل تنفيذ العمل": "Work progress", "تحديث حالة المهمة": "Update job status", "موقع الفني المباشر": "Live technician location", "الحالة الحالية": "Current status", "في الطريق • وصول 5 دقائق": "On the way • Arrives in 5 minutes", "تحديث مباشر": "Live update", "متابعة الطلب مع الفني": "Follow up with technician",
  "كل المحادثات": "All conversations", "رسائل العملاء": "Customer messages", "تواصل آمن مع فنيي عَمِّرها": "Secure chat with AMMERHA technicians", "تواصل آمن حول طلبات الصيانة فقط": "Secure chat about service requests only", "موضوع المحادثة": "Conversation topic", "إشعاراتك خاصة ومحمية داخل عَمِّرها": "Your notifications are private and protected in AMMERHA", "جميع محادثاتك محمية داخل عَمِّرها": "All conversations are protected in AMMERHA", "مراسلة العميل داخل عَمِّرها": "Message the customer in AMMERHA",
  "قيّم تجربتك مع الفني": "Rate your experience with the technician", "التقييم العام من 1 إلى 5": "Overall rating from 1 to 5", "ملاحظتك (اختياري)": "Your note (optional)", "آراء أهل القدس": "Jerusalem customer reviews", "عرض الملف والتقييمات": "View profile and ratings", "عرض الفاتورة والتقييم": "View invoice and rating",
  "حسابك موثق بالكامل": "Your account is fully verified", "موثق بالهوية": "Identity verified", "هوية وشهادة مهنية موثقتان": "Verified identity and professional certificate", "ملفي المهني": "My professional profile", "نبذة عني": "About me", "تخصصاتي": "My specialties", "مناطق العمل": "Service areas", "الخدمات": "Services", "أعمال قبل وبعد": "Before and after work", "قبل وبعد الصيانة": "Before and after service", "معرض الأعمال الموثقة": "Verified work gallery", "تعديل الملف والخدمات": "Edit profile and services",
  "استقبال طلبات جديدة": "Accept new requests", "طلبات صيانة قريبة ومحمية داخل عَمِّرها": "Nearby requests protected inside AMMERHA", "طلبات صيانة قريبة": "Nearby service requests", "متاح الآن": "Available now", "جديد الآن": "New now", "كل الحالات ضمن هذا الفلتر تمت معالجتها.": "All cases in this filter have been handled.", "لا توجد طلبات ضمن هذا الفلتر": "No requests in this filter", "لا توجد طلبات مطابقة": "No matching requests", "لا توجد محادثات مطابقة": "No matching conversations", "لا توجد أعمال في هذه القائمة": "No jobs in this list", "لا توجد حالات هنا": "No cases here",
  "عَمِّرها Pro": "AMMERHA Pro", "عَمِّرها Pro مفعّل": "AMMERHA Pro active", "اشتراكك Pro فعّال": "Your Pro subscription is active", "ميزة عَمِّرها Pro": "AMMERHA Pro feature", "هذه الميزة خاصة بـ Pro": "This is a Pro feature", "مزايا اشتراك عَمِّرها Pro": "AMMERHA Pro benefits", "تميّز ووصل لطلبات أكثر": "Stand out and reach more requests", "شو بتحصل مع Pro؟": "What do you get with Pro?", "إدارة الاشتراك والدفع": "Manage subscription", "إلغاء في أي وقت": "Cancel anytime", "جرّب المساعد الذكي": "Try the smart assistant",
  "الأدلة والبيانات": "Evidence & data", "التعرف على Pro": "Explore Pro", "إدارة المهام والأرباح والتوثيق": "Manage jobs, earnings, and verification", "الأرباح والمحفظة": "Earnings & wallet", "الرصيد المتاح للسحب": "Available balance", "سحب الرصيد": "Withdraw balance", "آخر الحركات": "Recent activity", "آخر الحركات المالية": "Recent transactions", "صافي إيرادات هذا الشهر": "Net revenue this month",
  "لوحة الإدارة": "Admin dashboard", "طلبات توثيق بانتظارك": "Verification requests waiting", "حالات في الطابور": "Cases in queue", "تنبيهات الذكاء للمخاطر": "AI risk alerts", "بدء التدقيق": "Start review", "مراجعة": "Review", "اعتماد": "Approve", "طلب استكمال": "Request more information", "تجميد": "Freeze", "تصعيد": "Escalate", "معالجة البلاغ": "Handle report", "توصية نظام المخاطر": "Risk system recommendation", "تم توثيق القرار": "Decision recorded", "تصدير التقرير المالي": "Export finance report", "تصدير سجل الرقابة": "Export audit log",
  "عرض التفاصيل": "View details", "عرض الكل": "View all", "فتح": "Open", "خروج": "Sign out", "العودة لاختيار الدور": "Return to role selection", "العودة للوحة الفني": "Back to technician dashboard", "اليوم": "Today", "سابقاً": "Earlier", "الجارية": "Active", "المكتملة": "Completed", "جاهز": "Ready", "عادي": "Standard", "مباشر": "Live", "غير مقروءة": "Unread", "الخصوصية": "Privacy", "الخطوة التالية": "Next step", "الرسالة الناتجة": "Generated message", "المشكلة المسجلة": "Recorded issue", "فهمنا من حكيك": "What we understood", "بالشيكل": "In shekels", "₪ شيكل": "₪ shekels", "العميل:": "Customer:", "الفني:": "Technician:", "الموقع:": "Location:", "موقعك:": "Your location:", "الوصول المتوقع:": "Expected arrival:",
  "نحن هنا لمساعدتك": "We are here to help", "سنخبرك فوراً بأي تحديث على طلبات الصيانة": "We will notify you about request updates", "كل جديد في طلباتك ومكافآتك": "Updates for your requests and rewards", "البلدة القديمة، القدس": "Old City, Jerusalem", "واد الجوز": "Wadi al-Joz", "عضو عَمِّرها الذهبي": "AMMERHA Gold member", "نقطة مكافأة": "reward points", "فنيون مفضلون": "favorite technicians", "عَمِّرها القدس": "AMMERHA Jerusalem", "من قلب القدس نبنيها بأيدينا": "Built in Jerusalem, by Jerusalem"
  , "ابحث عن طلب أو فني": "Search requests or technicians", "ابحث عن فني أو محادثة": "Search technicians or conversations", "ابحث عن طلب صيانة": "Search service requests", "ابحث": "Search", "اكتب رسالتك": "Write a message", "اكتب ملاحظتك هنا": "Write your note here", "اكتب وصف المشكلة": "Describe the issue", "السعر المقترح": "Suggested price", "مدة العمل المتوقعة": "Expected work duration"
  , "الكل": "All", "كل الطلبات": "All requests", "السابقة": "Previous", "الفنيون": "Technicians", "العملاء": "Customers", "سباكة": "Plumbing", "سباكة وصحية": "Plumbing", "كهرباء": "Electrical", "تكييف": "Air conditioning", "تكييف وتبريد": "Air conditioning", "نجارة": "Carpentry", "أجهزة منزلية": "Home appliances", "إلكترونيات": "Electronics", "صيانة عامة": "General maintenance", "عاجل": "Urgent", "مستعجل": "Urgent", "طارئ جداً": "Emergency", "غداً": "Tomorrow", "بأقرب وقت": "As soon as possible",
  "تسريب سيفون تحت المجلى": "Leaking drain under the sink", "تنظيف وصيانة المكيّف": "Air conditioner service", "إصلاح قاطع الكهرباء الرئيسي": "Main breaker repair", "إصلاح باب خزانة المطبخ": "Kitchen cabinet door repair", "المكيّف لا يبرّد ويصدر صوتاً": "Air conditioner is noisy and not cooling", "القاطع الرئيسي يفصل باستمرار": "Main breaker keeps tripping", "باب خزانة المطبخ مكسور": "Kitchen cabinet door is broken", "صيانة سخان مياه": "Water heater service", "إصلاح مضخة مياه": "Water pump repair",
  "الفني في الطريق": "Technician is on the way", "موعد محجوز": "Appointment scheduled", "مكتمل": "Completed", "ملغي": "Cancelled", "في الطريق": "On the way", "الوصول خلال 5–7 دقائق": "Arrives in 5–7 minutes", "تم التنفيذ والتقييم بنجاح": "Completed and rated", "أُلغي قبل قبول أي عرض": "Cancelled before accepting an offer",
  "البلدة القديمة": "Old City", "الشيخ جراح": "Sheikh Jarrah", "بيت حنينا": "Beit Hanina", "سلوان": "Silwan", "الطور": "At-Tur", "شعفاط": "Shuafat", "وادي الجوز": "Wadi al-Joz", "عقبة الخالدية، البلدة القديمة": "Aqabat al-Khalidiya, Old City", "وادي الجوز، القدس": "Wadi al-Joz, Jerusalem", "الشيخ جراح، القدس": "Sheikh Jarrah, Jerusalem", "سلوان، القدس": "Silwan, Jerusalem",
  "مركز المخاطر": "Risk center", "توثيق الفنيين": "Technician verification", "البلاغات والسلامة": "Reports & safety", "المالية والعمولات": "Finance & fees", "المستخدمون والفنيون": "Users & technicians", "سجل الرقابة": "Audit log", "إدارة عَمِّرها المركزية": "AMMERHA central administration", "لوحة مكافحة الاحتيال والرقابة المالية": "Fraud prevention and financial oversight", "عمولات اليوم": "Today's fees", "مشتركو Pro": "Pro subscribers", "أمان العمليات": "Transaction safety",
  "محاولة دفع خارج المنصة": "Attempted off-platform payment", "معدل إلغاء مرتفع بعد الوصول": "High cancellation rate after arrival", "بلاغ تأخر عن الموعد": "Late arrival report", "وصف طلب غير دقيق": "Inaccurate request description", "فني تكييف وتبريد": "Air conditioning technician", "فنية كهرباء منزلية": "Residential electrician", "فني سباكة": "Plumber", "فني تكييف": "AC technician", "فني صيانة": "Maintenance technician", "عميل": "Customer", "موثق • Pro": "Verified • Pro", "بانتظار التوثيق": "Awaiting verification", "نشط": "Active", "قيد التدقيق": "Under review",
  "اعتماد هوية فني": "Technician identity approved", "بدء تدقيق مخاطر": "Risk review started", "توجيه إنذار خصوصية": "Privacy warning issued", "إغلاق بلاغ عميل": "Customer report closed", "المشرف نور": "Admin Nour", "النظام الذكي": "Smart system", "المشرف سامر": "Admin Samer", "فريق السلامة": "Safety team",
  "الموقع تقريبي حتى قبول العميل للعرض": "Location remains approximate until the customer accepts", "خصوصية العميل محمية": "Customer privacy protected", "هوية محمية": "Protected identity", "إرسال التقييم": "Submit rating", "العودة للمكافآت": "Back to rewards", "إعادة المحاولة": "Try again", "الانتقال للعروض": "Continue to offers", "متابعة للعروض": "Continue to offers", "العودة للخريطة": "Back to map", "قبول العرض": "Accept offer", "عرض ملف الفني": "View technician profile", "رجوع": "Back"
  , "آخر تحديث: اليوم 10:30 ص": "Last updated: today at 10:30", "2 حالة تتطلب المراجعة الآن": "2 cases need review now", "آخر تحديث:": "Last updated:", "عن الشهر الماضي": "from last month", "عملية": "jobs", "دقيقة للوصول": "minutes away", "متر": "meters away", "₪ / شهر": "₪ / month",
  "احكي الآن… الصوت المقدسي الذكي سامعك": "Speak now… Jerusalem Smart Voice is listening", "احكيها بلهجتك، وإحنا بنرتّب عرضك باحتراف": "Speak naturally and we will craft a professional offer", "الصوت المقدسي الذكي": "Jerusalem Smart Voice", "التفريغ الصوتي التلقائي:": "Automatic transcription:", "بنرتّب حكيك ونحوّله لعرض واضح ومحترف…": "Turning your words into a clear professional offer…", "تحليل جبر الذكي": "Smart repair analysis",
  "اختر الخدمات والمناطق التي تريد استقبال طلبات منها على الخريطة.": "Choose the services and areas where you want to receive requests.", "أدوات مهنية تزيد ظهورك وتساعدك ترسل عروض أوضح وأسرع.": "Professional tools that improve visibility and help you send clearer offers faster.", "اضغط التسجيل واحكِ المشكلة بطريقتك، وسنرتب التفاصيل تلقائيًا.": "Tap record and describe the issue naturally; we will organize the details.", "اضغط على المايك واحكي للعميل شو فهمت، متى بتوصل، وكم بدك وقت.": "Tap the microphone and tell the customer what you understood, when you can arrive, and how long it will take.",
  "الحالة غير موجودة": "Case not found", "السعر العادل غير متاح لهذا الطلب.": "Fair price is unavailable for this request.", "السعر العادل في المنطقة": "Fair price in this area", "الفني المسؤول": "Assigned technician", "الميزة": "Feature", "تفاصيل العمل": "Job details", "حالة الطلب الحالية": "Current request status", "نشاط آخر 7 أيام": "Last 7 days activity", "صاحب الحالة والموقع": "Case owner & location",
  "أولوية الظهور 3x + مساعد العروض الذكي": "3× priority visibility + smart offer assistant", "أولوية الظهور والمساعد الذكي وتقارير الأداء": "Priority visibility, smart assistant, and performance reports", "باقي 150 نقطة لتحصل على قسيمة إضافية": "150 points to your next voucher", "بصوتك أو بالصورة • تشخيص فوري": "Voice or photo • instant diagnosis", "تسعير موثوق": "Reliable pricing", "سعر ورسالة وقطع مقترحة بالذكاء الاصطناعي": "AI suggested price, message, and parts", "صياغة عرض بمساعد Pro": "Draft with the Pro assistant", "يقترح السعر والقطع ونص الرد": "Suggests price, parts, and reply text", "فعّل الاشتراك للحصول على تشخيص وسعر ورسالة عرض مقترحة.": "Activate Pro for a suggested diagnosis, price, and offer message.",
  "بعض المساعدة الذكية غير متاحة الآن. تفاصيل طلبك محفوظة ويمكنك المتابعة.": "Some smart assistance is unavailable. Your request is saved and you can continue.", "تعذر العثور على الطلب": "Request not found", "تعذر العثور على العمل": "Job not found", "تعذر تحليل التسجيل. جرّب مرة ثانية.": "The recording could not be analyzed. Try again.", "تعذر تشغيل المساعد الآن": "The assistant is unavailable", "يمكنك متابعة إنشاء العرض يدوياً.": "You can continue creating the offer manually.", "تم اعتماد الرسالة والسعر المقترح في العرض بالأسفل.": "The suggested message and price were applied below.", "نراجع الوصف ونقدّر القطع والمدة والسعر العادل.": "Reviewing the description and estimating parts, duration, and fair price.",
  "تظهر الرسالة داخل التطبيق فقط. لا تضف رقم هاتف أو رابط تواصل خارجي.": "The message stays in the app. Do not add a phone number or external link.", "تظهر لك هوية مختصرة: الاسم الأول والمشكلة فقط. لا نعرض رقم الهاتف أو بيانات التواصل الخارجية.": "You only see the first name and issue. Phone and external contact details stay hidden.", "بيانات العملاء لا تُحفظ في حسابك ولا تظهر خارج طلباتهم داخل عَمِّرها.": "Customer data is not stored in your profile or shown outside AMMERHA requests.", "سيتم إعلامك داخل عَمِّرها عند قبول العرض، ولن تظهر بيانات التواصل الخاصة بالعميل.": "AMMERHA will notify you when the offer is accepted; customer contact details remain hidden.", "سيتم منع الأرقام وروابط التواصل الخارجي تلقائياً.": "Phone numbers and external links are blocked automatically.", "لا يمكن تعطيل حماية بيانات العملاء أو مشاركة أرقام الهواتف خارج التطبيق.": "Customer privacy protection cannot be disabled or used to share phone numbers.", "لأمانك وضمان حقوقك، تتم جميع الاتفاقات عبر عَمِّرها دون مشاركة أرقام الهواتف.": "For safety and protection, all agreements stay inside AMMERHA without sharing phone numbers.", "لضمان حقك، لا تشارك رقمك ولا تطلب من العميل التواصل خارج عَمِّرها.": "To protect your rights, keep communication inside AMMERHA.",
  "تابع كل طلبات الصيانة من مكان واحد": "Track all service requests in one place", "سيحلّل الذكاء الاصطناعي الطلب ويقترح السعر العادل، ثم يرسله للفنيين الأقرب.": "AI analyzes the request, suggests a fair price, and sends it to nearby technicians.", "حسب تصميم Stitch، المساعد الذكي يقترح تشخيصاً وسعراً عادلاً ورسالة عرض جاهزة.": "The smart assistant suggests a diagnosis, fair price, and ready offer message.", "دعم مخصص للفنيين وحماية الحقوق في كل طلب.": "Dedicated technician support and protection on every request.", "دفع آمن وضمان عَمِّرها على تنفيذ العمل": "Secure payment and AMMERHA service protection", "رفع وثيقة جديدة": "Upload a new document", "عرض توثيق العمل والفاتورة": "View work proof and invoice", "شيكل إسرائيلي (NIS)": "Israeli shekel (NIS)",
  "توثيق صيانة حقيقية تم تنفيذها الأسبوع الماضي في حارة السعدية بالبلدة القديمة.": "Verified work completed last week in the Old City.", "صيانة موثقة عبر عَمِّرها": "Service verified by AMMERHA", "فحص معتمد": "Verified inspection", "فني سباكة معتمد بخبرة 9 سنوات في بيوت القدس، متخصص في كشف التسريبات وصيانة المطابخ والحمامات بسرعة ونظافة.": "Verified plumber with 9 years of experience in Jerusalem homes, specializing in leak detection and clean kitchen and bathroom repairs.", "فني سباكة وصحية • البلدة القديمة": "Plumber • Old City", "قبل": "Before", "بعد": "After", "قبل: تسريب وصدأ": "Before: leak and rust", "بعد: عزل وإصلاح متقن": "After: sealed and repaired", "قراءة الكل": "Mark all read", "محدد تلقائياً": "Selected automatically", "عضوية منذ 3 سنوات • القدس": "Member for 3 years • Jerusalem", "عَمِّرها • الإصدار 1.0.0": "AMMERHA • Version 1.0.0",
  "هوية محمية: لا يظهر رقم الهاتف أو العنوان. الاتفاق والدفع داخل عَمِّرها فقط.": "Protected identity: phone and address stay hidden. Agreements remain inside AMMERHA.", "هويتك وشهاداتك المهنية معتمدة لدى عَمِّرها.": "Your identity and professional certificates are verified by AMMERHA.", "وثّق صور قبل وبعد كل عمل لرفع ثقة العملاء بملفك المهني.": "Add before and after photos to build trust in your professional profile.", "يؤكد الفني طبيعة العطل عند المعاينة.": "The technician confirms the issue during inspection.", "يتجدد في 18 تشرين الأول 2026": "Renews October 18, 2026", "يحمي عَمِّرها حقك وحق العميل عند إبقاء الاتفاق والدفع والمراسلة داخل التطبيق.": "AMMERHA protects both sides when agreements and messages stay in the app.", "يسجل عَمِّرها المشرف والوقت والحالة المستهدفة لكل قرار لحماية العدالة والشفافية.": "AMMERHA records the admin, time, and target state for every decision.", "يظهر الاسم الأول والمنطقة التقريبية فقط. العنوان الدقيق يُكشف بعد قبول العرض.": "Only the first name and approximate area are shown until an offer is accepted."
};

const patterns: ReadonlyArray<[RegExp, string]> = [
  [/^طلب رقم (.+)$/, "Request $1"], [/^العميل: (.+)$/, "Customer: $1"], [/^الفني: (.+)$/, "Technician: $1"], [/^السعر المتفق عليه: (.+)$/, "Agreed price: $1"], [/^الوصول المتوقع: (.+)$/, "Expected arrival: $1"], [/^الموقع: (.+)$/, "Location: $1"], [/^موقعك: (.+)$/, "Your location: $1"], [/^رقم الطلب: (.+)$/, "Request ID: $1"], [/^المرفقات \((.+)\)$/, "Attachments ($1)"], [/^العروض المتاحة \((.+)\)$/, "Available offers ($1)"], [/^طلب صيانة مع (.+)$/, "Service request with $1"], [/^طلب قريب منك • (.+)$/, "Nearby request • $1"]
];

export function translateLegacyLiteral(value: string): string {
  const trimmed = value.trim();
  const translated = exact[trimmed];
  if (translated) return value.replace(trimmed, translated);
  for (const [pattern, replacement] of patterns) if (pattern.test(trimmed)) return value.replace(trimmed, trimmed.replace(pattern, replacement));
  return value;
}
