import { DemoChatRepository } from "../demo/adapters/demoChatRepository";
import { DemoJobRepository } from "../demo/adapters/demoJobRepository";
import { DemoNotificationRepository } from "../demo/adapters/demoNotificationRepository";
import { DemoOfferRepository } from "../demo/adapters/DemoOfferRepository";
import { DemoRepairRequestRepository } from "../demo/adapters/demoRepairRequestRepository";
import { DemoReviewRepository } from "../demo/adapters/demoReviewRepository";
import { DemoRewardRepository } from "../demo/adapters/demoRewardRepository";
import { DemoTechnicianRepository } from "../demo/adapters/DemoTechnicianRepository";
import { selectRepository } from "./api/repositoryMode";
import { ApiChatRepository } from "./api/repositories/ApiChatRepository";
import { ApiJobRepository } from "./api/repositories/ApiJobRepository";
import { ApiNotificationRepository } from "./api/repositories/ApiNotificationRepository";
import { ApiOfferRepository } from "./api/repositories/ApiOfferRepository";
import { ApiRepairRequestRepository } from "./api/repositories/ApiRepairRequestRepository";
import { ApiReviewRepository } from "./api/repositories/ApiReviewRepository";
import { ApiRewardRepository } from "./api/repositories/ApiRewardRepository";
import { ApiTechnicianRepository } from "./api/repositories/ApiTechnicianRepository";
import type { OfferRepository } from "../domain/contracts/offerRepository";
import type { ChatRepository } from "../domain/contracts/chatRepository";
import type { RepairRequestRepository } from "../domain/contracts/repairRequestRepository";

const demoOffers = new DemoOfferRepository();
export const technicianRepository = selectRepository(new ApiTechnicianRepository(), new DemoTechnicianRepository());
export const repairRequestRepository = selectRepository<RepairRequestRepository>(new ApiRepairRequestRepository(), new DemoRepairRequestRepository());
export const offerRepository = selectRepository<OfferRepository>(new ApiOfferRepository(), demoOffers);
export const resetOfferRepository = () => demoOffers.reset();
export const customerJobRepository = selectRepository(new ApiJobRepository("customer"), new DemoJobRepository());
export const technicianJobRepository = selectRepository(new ApiJobRepository("technician"), new DemoJobRepository());
export const customerChatRepository = selectRepository<ChatRepository>(new ApiChatRepository("customer"), new DemoChatRepository());
export const technicianChatRepository = selectRepository<ChatRepository>(new ApiChatRepository("technician"), new DemoChatRepository());
export const reviewRepository = selectRepository(new ApiReviewRepository(), new DemoReviewRepository());
export const rewardRepository = selectRepository(new ApiRewardRepository(), new DemoRewardRepository());
export const notificationRepository = selectRepository(new ApiNotificationRepository(), new DemoNotificationRepository());
