import { useEffect, useState } from "react";
import { Pressable, Text, TextInput, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import type { CustomerStackParamList } from "../../../app/navigation/navigation.types";
import { Button, EmptyState, ErrorState, LoadingState, ScreenContainer } from "../../../shared/components";
import { chatRepository } from "../../../demo/adapters/demoChatRepository";
import type { ChatMessage } from "../../../domain/contracts/chatRepository";
export function CustomerChatScreen({ route, navigation }: NativeStackScreenProps<CustomerStackParamList, "CustomerChat">) {
  const [messages, setMessages] = useState<readonly ChatMessage[]>([]); const [text, setText] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  useEffect(() => { chatRepository.getMessages(route.params.jobId).then(setMessages).catch(() => setError(true)).finally(() => setLoading(false)); }, [route.params.jobId]);
  const send = async (value: string) => { if (!value.trim()) return; try { const message = await chatRepository.send(route.params.jobId, value.trim()); setMessages((current) => [...current, message]); setText(""); } catch { setError(true); } };
  return <ScreenContainer><Text style={styles.title}>محادثة مع الفني</Text><Text style={styles.subtitle}>طارق المقدسي · مهمة التسريب</Text>{loading ? <LoadingState /> : error ? <ErrorState message="تعذر تحميل المحادثة." /> : !messages.length ? <EmptyState message="لا توجد رسائل بعد." /> : messages.map((message) => <View key={message.id} style={[styles.bubble, message.sender === "customer" ? styles.customer : styles.technician]}><Text style={styles.message}>{message.text}</Text><Text style={styles.time}>{message.createdAt} · {message.sender === "customer" ? "تم الإرسال" : "الفني"}</Text></View>)}<TextInput value={text} onChangeText={setText} placeholder="اكتب رسالتك…" style={styles.input} multiline /><View style={styles.actions}><Button onPress={() => void send(text)}>إرسال</Button><Button variant="outlined" onPress={() => void send("📷 صورة مرفقة من موقع التسريب")}>إرفاق صورة</Button><Button variant="outlined" onPress={() => void send("📍 مشاركة الموقع: البلدة القديمة")}>مشاركة الموقع</Button></View><Pressable onPress={() => navigation.goBack()}><Text style={styles.back}>العودة إلى المهمة</Text></Pressable></ScreenContainer>;
}
const styles = { title: { fontSize: 22, fontWeight: "700" as const, textAlign: "right" as const, writingDirection: "rtl" as const }, subtitle: { textAlign: "right" as const, writingDirection: "rtl" as const, marginBottom: 12 }, bubble: { borderRadius: 14, padding: 12, marginVertical: 5, maxWidth: "88%" as const }, customer: { alignSelf: "flex-start" as const, backgroundColor: "#F3E7C4" }, technician: { alignSelf: "flex-end" as const, backgroundColor: "#FFF" }, message: { textAlign: "right" as const, writingDirection: "rtl" as const, fontSize: 16 }, time: { textAlign: "right" as const, color: "#777", fontSize: 11, marginTop: 4 }, input: { backgroundColor: "#FFF" as const, borderColor: "#DDD", borderRadius: 12, borderWidth: 1, minHeight: 48, padding: 12, textAlign: "right" as const, writingDirection: "rtl" as const, marginTop: 12 }, actions: { gap: 8, marginVertical: 12 }, back: { textAlign: "center" as const, color: "#8A641F", marginTop: 8 } };
