import { LocalizedTextInput } from "../../../shared/i18n/LocalizedTextInput";
import { LocalizedText } from "../../../shared/i18n/LocalizedText";
import { useEffect, useState } from "react";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Text, TextInput } from "react-native";
import type { CustomerStackParamList } from "../../../app/navigation/navigation.types";
import { Button, Card, ScreenContainer, SuccessState } from "../../../shared/components";
import { reviewRepository } from "../../../demo/adapters/demoReviewRepository";
export function CustomerRatingScreen({ route, navigation }: NativeStackScreenProps<CustomerStackParamList, "CustomerRating">) { const [rating, setRating] = useState("5"); const [comment, setComment] = useState(""); const [done, setDone] = useState(false); const [reviewed, setReviewed] = useState(false); useEffect(() => { void reviewRepository.getForJob(route.params.jobId).then((review) => setReviewed(Boolean(review))); }, [route.params.jobId]); if (done || reviewed) return <ScreenContainer><SuccessState message={done ? "شكراً لتقييمك. أضفنا نقاط المكافأة إلى حسابك." : "تم إرسال تقييم هذه المهمة مسبقاً."} /><Button onPress={() => navigation.popTo("CustomerTabs")}>العودة للمكافآت</Button></ScreenContainer>; return <ScreenContainer><LocalizedText style={styles.title}>قيّم تجربتك مع الفني</LocalizedText><Card><LocalizedText style={styles.text}>التقييم العام من 1 إلى 5</LocalizedText><LocalizedTextInput value={rating} onChangeText={setRating} keyboardType="number-pad" style={styles.input} /><LocalizedText style={styles.text}>ملاحظتك (اختياري)</LocalizedText><LocalizedTextInput value={comment} onChangeText={setComment} multiline style={[styles.input, { height: 90 }]} /></Card><Button disabled={reviewed} onPress={async () => { if (reviewed) return; await reviewRepository.submit({ jobId: route.params.jobId, technicianId: route.params.technicianId, overall: Number(rating), quality: Number(rating), speed: Number(rating), commitment: Number(rating), communication: Number(rating), comment }); setDone(true); setReviewed(true); }}>إرسال التقييم</Button></ScreenContainer>; }
const styles = { title: { fontSize: 22, fontWeight: "700" as const, textAlign: "right" as const, writingDirection: "rtl" as const }, text: { textAlign: "right" as const, writingDirection: "rtl" as const, marginVertical: 8 }, input: { borderWidth: 1, borderColor: "#ddd", borderRadius: 10, padding: 12, textAlign: "right" as const, writingDirection: "rtl" as const } };
