import { LocalizedText } from "../../../shared/i18n/LocalizedText";
import { useEffect, useState } from "react";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Text, View } from "react-native";
import type { CustomerStackParamList } from "../../../app/navigation/navigation.types";
import { Badge, Button, Card, LoadingState, ScreenContainer } from "../../../shared/components";
import { customerJobRepository as jobRepository } from "../../../services/repositories";
import { newStatus, statusLabel } from "../services/jobStatus";
import type { Job } from "../../../domain/models/job";
export function CustomerJobScreen({ route, navigation }: NativeStackScreenProps<CustomerStackParamList, "CustomerJob">) { const [job, setJob] = useState<Job>(); useEffect(() => { void jobRepository.getJob(route.params.jobId).then(setJob); }, [route.params.jobId]); if (!job) return <ScreenContainer><LoadingState /></ScreenContainer>; return <ScreenContainer><LocalizedText style={styles.title}>المهمة النشطة</LocalizedText><Card><Badge label={statusLabel[job.status]} /><LocalizedText style={styles.text}>الفني: طارق المقدسي</LocalizedText><LocalizedText style={styles.text}>السعر المتفق عليه: {job.agreedPrice} ₪</LocalizedText><LocalizedText style={styles.text}>الموقع: {job.locationLabel}</LocalizedText><LocalizedText style={styles.text}>الوصول المتوقع: {job.expectedArrival}</LocalizedText></Card><LocalizedText style={styles.title}>تقدم المهمة</LocalizedText>{(["accepted", "on_the_way", "in_progress", "completed"] as const).map((step) => <Card key={step}><LocalizedText style={styles.text}>{statusLabel[step]} {step === job.status ? "• الآن" : ""}</LocalizedText></Card>)}{job.status !== "completed" ? <Button onPress={async () => setJob(await jobRepository.updateStatus(job.id, newStatus(job.status)))}>محاكاة التقدم: {statusLabel[newStatus(job.status)]}</Button> : <Button onPress={() => navigation.navigate("CustomerRating", { jobId: job.id, technicianId: job.technicianId })}>تقييم الفني</Button>}<Button variant="secondary" onPress={() => navigation.navigate("CustomerChat", { jobId: job.id, requestId: job.requestId, technicianId: job.technicianId })}>فتح المحادثة مع الفني</Button><Button variant="outlined" onPress={() => navigation.navigate("CustomerNotifications")}>التنبيهات</Button></ScreenContainer>; }
const styles = { title: { fontSize: 22, fontWeight: "700" as const, textAlign: "right" as const, marginBottom: 12, writingDirection: "rtl" as const }, text: { fontSize: 16, textAlign: "right" as const, writingDirection: "rtl" as const, marginVertical: 5 } };
