import { Ionicons } from "@expo/vector-icons";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import type { TechnicianStackParamList } from "../../../app/navigation/navigation.types";
import { colors, shadows, typography } from "../../../shared/theme";
import { getTechnicianRequest } from "../technicianData";

export function TechnicianRequestScreen({ navigation, route }: NativeStackScreenProps<TechnicianStackParamList, "TechnicianRequestDetails">) {
  const request = getTechnicianRequest(route.params.requestId);
  if (!request) return <SafeAreaView style={styles.safe}><View style={styles.empty}><Text style={styles.title}>تعذر العثور على الطلب</Text></View></SafeAreaView>;

  return <SafeAreaView edges={["top", "bottom"]} style={styles.safe}>
    <View style={styles.header}><Pressable onPress={() => navigation.goBack()} style={styles.back}><Ionicons name="arrow-forward" size={18} color="#475569" /></Pressable><View style={styles.headerCopy}><Text style={styles.headerTitle}>تفاصيل طلب الصيانة</Text><Text style={styles.headerSubtitle}>طلب قريب منك • {request.createdAt}</Text></View><View style={styles.urgent}><Text style={styles.urgentText}>{request.urgency}</Text></View></View>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.privacy}><Ionicons name="shield-checkmark" size={18} color="#176B51" /><View style={styles.privacyCopy}><Text style={styles.privacyTitle}>خصوصية العميل محمية</Text><Text style={styles.privacyText}>يظهر الاسم الأول والمنطقة التقريبية فقط. العنوان الدقيق يُكشف بعد قبول العرض.</Text></View></View>
      <View style={styles.card}><View style={styles.categoryRow}><View style={styles.category}><Ionicons name="water" size={14} color="#8C6D14" /><Text style={styles.categoryText}>{request.category}</Text></View><Text style={styles.time}>{request.createdAt}</Text></View><Text style={styles.problem}>{request.problem}</Text><Text style={styles.description}>{request.description}</Text><View style={styles.customerRow}><View style={styles.customerAvatar}><Ionicons name="person" size={19} color={colors.primary} /></View><View style={styles.customerCopy}><Text style={styles.customerName}>العميل: {request.customerName}</Text><Text style={styles.customerMeta}>{request.area} • على بعد {request.distanceKm} كم</Text></View><Ionicons name="lock-closed" size={14} color="#94A3B8" /></View></View>
      <View style={styles.metrics}><Metric icon="cash-outline" label="السعر العادل" value={request.fairPrice} color="#047857" /><Metric icon="navigate-outline" label="المسافة" value={`${request.distanceKm} كم`} color="#1D4ED8" /><Metric icon="flash-outline" label="الأولوية" value={request.urgency} color="#BE123C" /></View>
      <View style={styles.card}><Text style={styles.sectionTitle}>تحليل أولي للعطل</Text><Detail label="التشخيص المحتمل" value="سيفون حوض المطبخ أو وصلة التصريف" /><Detail label="القطع المتوقعة" value="سيفون مرن 1.5 إنش + جوانات عزل" /><Detail label="مدة التنفيذ" value="30–45 دقيقة" /><View style={styles.fair}><Ionicons name="checkmark-circle" size={15} color="#047857" /><Text style={styles.fairText}>السعر المقترح ضمن متوسط صيانة القدس</Text></View></View>
      <Pressable onPress={() => navigation.navigate("TechnicianAiAssistant", { requestId: request.id })} style={styles.aiButton}><Ionicons name="sparkles" size={19} color="#8C6D14" /><View style={styles.aiCopy}><Text style={styles.aiTitle}>صياغة عرض بمساعد Pro</Text><Text style={styles.aiText}>سعر ورسالة وقطع مقترحة بالذكاء الاصطناعي</Text></View><Ionicons name="chevron-back" size={18} color="#8C6D14" /></Pressable>
      <Pressable onPress={() => navigation.navigate("TechnicianCreateOffer", { requestId: request.id })} style={styles.primary}><Ionicons name="send" size={18} color={colors.text} /><Text style={styles.primaryText}>إنشاء عرض يدوي وإرساله</Text></Pressable>
    </ScrollView>
  </SafeAreaView>;
}

function Metric({ icon, label, value, color }: { icon: keyof typeof Ionicons.glyphMap; label: string; value: string; color: string }) { return <View style={styles.metric}><Ionicons name={icon} size={16} color={color} /><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, { color }]}>{value}</Text></View>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View>; }

const styles = StyleSheet.create({
  safe: { backgroundColor: "#F8F7F4", flex: 1 }, header: { alignItems: "center", backgroundColor: "white", borderBottomColor: "#ECE7DC", borderBottomWidth: 1, flexDirection: "row-reverse", minHeight: 64, paddingHorizontal: 12 }, back: { alignItems: "center", backgroundColor: "#F1F5F9", borderRadius: 11, height: 34, justifyContent: "center", width: 34 }, headerCopy: { alignItems: "center", flex: 1 }, headerTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 14, fontWeight: "800" }, headerSubtitle: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 8 }, urgent: { backgroundColor: "#FFF1F2", borderRadius: 9, paddingHorizontal: 8, paddingVertical: 6 }, urgentText: { color: "#BE123C", fontFamily: typography.fontFamily, fontSize: 8, fontWeight: "700" }, content: { gap: 12, padding: 14, paddingBottom: 30 },
  privacy: { alignItems: "center", backgroundColor: "#ECFDF5", borderColor: "#A7E6CD", borderRadius: 15, borderWidth: 1, flexDirection: "row-reverse", gap: 8, padding: 11 }, privacyCopy: { flex: 1 }, privacyTitle: { color: "#176B51", fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800", textAlign: "right" }, privacyText: { color: "#397564", fontFamily: typography.fontFamily, fontSize: 8, lineHeight: 14, marginTop: 2, textAlign: "right" }, card: { ...shadows.subtle, backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 18, borderWidth: 1, padding: 13 }, categoryRow: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between" }, category: { alignItems: "center", backgroundColor: "#FFF8E3", borderRadius: 9, flexDirection: "row-reverse", gap: 4, paddingHorizontal: 8, paddingVertical: 5 }, categoryText: { color: "#8C6D14", fontFamily: typography.fontFamily, fontSize: 8, fontWeight: "700" }, time: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7 }, problem: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 16, fontWeight: "800", marginTop: 11, textAlign: "right" }, description: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 10, lineHeight: 18, marginTop: 6, textAlign: "right", writingDirection: "rtl" }, customerRow: { alignItems: "center", borderTopColor: "#F0ECE3", borderTopWidth: 1, flexDirection: "row-reverse", gap: 8, marginTop: 12, paddingTop: 11 }, customerAvatar: { alignItems: "center", backgroundColor: colors.secondary, borderRadius: 18, height: 36, justifyContent: "center", width: 36 }, customerCopy: { flex: 1 }, customerName: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "700", textAlign: "right" }, customerMeta: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 8, marginTop: 2, textAlign: "right" },
  metrics: { flexDirection: "row-reverse", gap: 7 }, metric: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 13, borderWidth: 1, flex: 1, padding: 9 }, metricLabel: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7, marginTop: 3 }, metricValue: { fontFamily: typography.fontFamily, fontSize: 9, fontWeight: "800", marginTop: 2, textAlign: "center" }, sectionTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 12, fontWeight: "800", marginBottom: 6, textAlign: "right" }, detail: { borderBottomColor: "#F0ECE3", borderBottomWidth: 1, flexDirection: "row-reverse", justifyContent: "space-between", paddingVertical: 8 }, detailLabel: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 9 }, detailValue: { color: colors.text, flex: 1, fontFamily: typography.fontFamily, fontSize: 9, fontWeight: "700", paddingLeft: 8, textAlign: "left" }, fair: { alignItems: "center", backgroundColor: "#ECFDF5", borderRadius: 10, flexDirection: "row-reverse", gap: 4, justifyContent: "center", marginTop: 9, padding: 8 }, fairText: { color: "#047857", fontFamily: typography.fontFamily, fontSize: 8, fontWeight: "700" },
  aiButton: { alignItems: "center", backgroundColor: "#FFF8E3", borderColor: "#EEDB9D", borderRadius: 15, borderWidth: 1, flexDirection: "row-reverse", gap: 8, padding: 11 }, aiCopy: { flex: 1 }, aiTitle: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 10, fontWeight: "800", textAlign: "right" }, aiText: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 8, marginTop: 2, textAlign: "right" }, primary: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 14, flexDirection: "row-reverse", gap: 7, justifyContent: "center", minHeight: 49 }, primaryText: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 11, fontWeight: "800" }, empty: { alignItems: "center", flex: 1, justifyContent: "center" }, title: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 16, fontWeight: "800" }
});
