import { Ionicons } from "@expo/vector-icons";
import { useNavigation } from "@react-navigation/native";
import type { NativeStackNavigationProp } from "@react-navigation/native-stack";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import type { TechnicianStackParamList } from "../../../app/navigation/navigation.types";
import { colors, shadows, typography } from "../../../shared/theme";
import { technicianConversations } from "../technicianData";

export function TechnicianMessagesScreen() {
  const navigation = useNavigation<NativeStackNavigationProp<TechnicianStackParamList>>();
  const [query, setQuery] = useState("");
  const [unreadOnly, setUnreadOnly] = useState(false);
  const conversations = useMemo(() => technicianConversations.filter((item) => (!unreadOnly || item.unread > 0) && (!query.trim() || `${item.customerName} ${item.problem}`.includes(query.trim()))), [query, unreadOnly]);

  return <SafeAreaView edges={["top"]} style={styles.safe}>
    <View style={styles.header}><View><Text style={styles.title}>رسائل العملاء</Text><Text style={styles.subtitle}>تواصل آمن حول طلبات الصيانة فقط</Text></View><View style={styles.headerIcon}><Ionicons name="chatbubbles" size={21} color={colors.primaryPressed} /></View></View>
    <View style={styles.privacy}><Ionicons name="shield-checkmark" size={17} color="#176B51" /><Text style={styles.privacyText}>تظهر لك هوية مختصرة: الاسم الأول والمشكلة فقط. لا نعرض رقم الهاتف أو بيانات التواصل الخارجية.</Text></View>
    <View style={styles.search}><Ionicons name="search" size={18} color="#94A3B8" /><TextInput value={query} onChangeText={setQuery} placeholder="ابحث باسم العميل أو المشكلة" placeholderTextColor="#94A3B8" style={styles.searchInput} /></View>
    <View style={styles.tabs}><Pressable onPress={() => setUnreadOnly(false)} style={[styles.tab, !unreadOnly && styles.activeTab]}><Text style={[styles.tabText, !unreadOnly && styles.activeTabText]}>كل المحادثات</Text></Pressable><Pressable onPress={() => setUnreadOnly(true)} style={[styles.tab, unreadOnly && styles.activeTab]}><Text style={[styles.tabText, unreadOnly && styles.activeTabText]}>غير مقروءة</Text></Pressable></View>
    <ScrollView contentContainerStyle={styles.list} showsVerticalScrollIndicator={false}>
      {conversations.map((conversation) => <Pressable key={conversation.id} onPress={() => navigation.navigate("TechnicianChat", { conversationId: conversation.id, requestId: conversation.requestId, customerName: conversation.customerName, problem: conversation.problem })} style={({ pressed }) => [styles.card, pressed && styles.pressed]}>
        <View style={styles.avatar}><Text style={styles.avatarText}>{conversation.customerName.charAt(0)}</Text><View style={styles.lock}><Ionicons name="lock-closed" size={8} color="white" /></View></View>
        <View style={styles.copy}><View style={styles.nameRow}><Text style={styles.name}>{conversation.customerName}</Text><View style={styles.privateBadge}><Text style={styles.privateText}>هوية محمية</Text></View></View><Text style={styles.problem}>{conversation.problem}</Text><Text numberOfLines={1} style={styles.message}>{conversation.lastMessage}</Text></View>
        <View style={styles.meta}><Text style={styles.time}>{conversation.time}</Text>{conversation.unread ? <View style={styles.unread}><Text style={styles.unreadText}>{conversation.unread}</Text></View> : <Ionicons name="checkmark-done" size={15} color="#10B981" />}</View>
      </Pressable>)}
      {!conversations.length ? <View style={styles.empty}><Ionicons name="chatbubble-ellipses-outline" size={36} color="#CBD5E1" /><Text style={styles.emptyText}>لا توجد محادثات مطابقة</Text></View> : null}
      <View style={styles.platformNote}><Ionicons name="warning-outline" size={16} color="#8C6D14" /><Text style={styles.platformText}>لضمان حقك، لا تشارك رقمك ولا تطلب من العميل التواصل خارج عَمِّرها.</Text></View>
    </ScrollView>
  </SafeAreaView>;
}

const styles = StyleSheet.create({
  safe: { backgroundColor: "#F8F7F4", flex: 1 }, header: { alignItems: "center", flexDirection: "row-reverse", justifyContent: "space-between", paddingBottom: 11, paddingHorizontal: 16, paddingTop: 10 }, title: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 22, fontWeight: "800", textAlign: "right" }, subtitle: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 9, textAlign: "right" }, headerIcon: { alignItems: "center", backgroundColor: "#FFF4C8", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, privacy: { alignItems: "center", backgroundColor: "#ECFDF5", borderColor: "#A7E6CD", borderRadius: 14, borderWidth: 1, flexDirection: "row-reverse", gap: 7, marginHorizontal: 14, padding: 10 }, privacyText: { color: "#176B51", flex: 1, fontFamily: typography.fontFamily, fontSize: 8, lineHeight: 14, textAlign: "right" }, search: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#E8E2D6", borderRadius: 14, borderWidth: 1, flexDirection: "row-reverse", gap: 8, marginHorizontal: 14, marginTop: 10, minHeight: 45, paddingHorizontal: 12 }, searchInput: { color: colors.text, flex: 1, fontFamily: typography.fontFamily, fontSize: 11, textAlign: "right", writingDirection: "rtl" }, tabs: { flexDirection: "row-reverse", gap: 7, paddingHorizontal: 14, paddingTop: 10 }, tab: { borderRadius: 11, paddingHorizontal: 12, paddingVertical: 7 }, activeTab: { backgroundColor: colors.secondary }, tabText: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 9, fontWeight: "600" }, activeTabText: { color: "white" }, list: { gap: 9, padding: 14, paddingBottom: 28 },
  card: { ...shadows.subtle, alignItems: "center", backgroundColor: "white", borderColor: "#ECE7DC", borderRadius: 17, borderWidth: 1, flexDirection: "row-reverse", gap: 10, minHeight: 88, padding: 11 }, pressed: { opacity: 0.72, transform: [{ scale: 0.985 }] }, avatar: { alignItems: "center", backgroundColor: colors.secondary, borderColor: colors.primary, borderRadius: 24, borderWidth: 1.5, height: 48, justifyContent: "center", position: "relative", width: 48 }, avatarText: { color: colors.primary, fontFamily: typography.fontFamily, fontSize: 18, fontWeight: "800" }, lock: { alignItems: "center", backgroundColor: "#047857", borderColor: "white", borderRadius: 7, borderWidth: 1.5, bottom: -2, height: 15, justifyContent: "center", position: "absolute", right: -2, width: 15 }, copy: { flex: 1 }, nameRow: { alignItems: "center", flexDirection: "row-reverse", gap: 5 }, name: { color: colors.text, fontFamily: typography.fontFamily, fontSize: 12, fontWeight: "700" }, privateBadge: { backgroundColor: "#ECFDF5", borderRadius: 6, paddingHorizontal: 5, paddingVertical: 2 }, privateText: { color: "#047857", fontFamily: typography.fontFamily, fontSize: 6, fontWeight: "700" }, problem: { color: "#8C6D14", fontFamily: typography.fontFamily, fontSize: 8, fontWeight: "700", marginTop: 3, textAlign: "right" }, message: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 8, marginTop: 3, textAlign: "right" }, meta: { alignItems: "center", alignSelf: "stretch", justifyContent: "space-between", paddingVertical: 4 }, time: { color: "#94A3B8", fontFamily: typography.fontFamily, fontSize: 7 }, unread: { alignItems: "center", backgroundColor: colors.primary, borderRadius: 9, height: 19, justifyContent: "center", width: 19 }, unreadText: { color: colors.text, fontSize: 8, fontWeight: "800" }, empty: { alignItems: "center", padding: 55 }, emptyText: { color: colors.textMuted, fontFamily: typography.fontFamily, fontSize: 10, marginTop: 6 }, platformNote: { alignItems: "center", backgroundColor: "#FFF8E3", borderColor: "#EEDB9D", borderRadius: 13, borderWidth: 1, flexDirection: "row-reverse", gap: 6, padding: 10 }, platformText: { color: "#8C6D14", flex: 1, fontFamily: typography.fontFamily, fontSize: 8, lineHeight: 14, textAlign: "right" }
});
