export { createMockAiService } from "./services/MockAiService";
export type { AiService } from "./services/AiService";
export { createSimulationAiService } from "./services/simulationAiService";
export type { AssistanceCategory, AssistanceRouteType, DiagnosisAnswer, DiagnosisInput, DiagnosisResult, FollowUpOption, FollowUpQuestion, RoutingRecommendation } from "./contracts/diagnosis.types";
export type { FairPriceInput, FairPriceResult } from "./contracts/fairPrice.types";
export type { TechnicianCandidate, TechnicianMatch, TechnicianRankingInput } from "./contracts/matching.types";
export type { OfferAssistantInput, OfferAssistantResult } from "./contracts/offerAssistant.types";
export type { RiskInput, RiskResult } from "./contracts/risk.types";
export type { StructuredVoiceRequest, VoiceRequestInput } from "./contracts/voice.types";
export { evaluateOffer } from "./engines/fair-price/priceEngine";
export { recommendAssistance } from "./engines/routing/routingEngine";
