export const ar = {
  common: { back: "رجوع", close: "إغلاق", save: "حفظ", retry: "إعادة المحاولة", loading: "جارٍ التحميل", selected: "محدد" },
  navigation: { home: "الرئيسية", requests: "طلباتي", messages: "الرسائل", rewards: "المكافآت", account: "حسابي", jobs: "أعمالي", mapRequests: "الخريطة والطلبات" },
  login: { welcome: "أهلاً بك في عَمِّرها", tagline: "من قلب القدس نبنيها بأيدينا", choose: "اختر طريقة الدخول", noAuth: "نسخة العرض لا تحتاج كلمة مرور أو إنشاء حساب", customer: "الدخول كعميل", customerHint: "اطلب صيانة وتابع الفني والعروض", technician: "الدخول كفني", technicianHint: "شاهد الطلبات وأعمالك ورسائلك", admin: "الدخول للإدارة", adminHint: "راقب المنصة والتوثيق والمخاطر", hint: "اختر أي دور لتجربة صفحاته مباشرة" },
  settings: { title: "إمكانية الوصول والمظهر", subtitle: "خصص عَمِّرها بالطريقة الأنسب لك", language: "اللغة", appearance: "المظهر", accessibility: "إمكانية الوصول", arabic: "العربية", english: "English", light: "فاتح", dark: "داكن فاخر", highContrast: "تباين عالٍ", system: "حسب الجهاز", largeText: "نص أكبر", largeTextHint: "يكبّر النصوص المهمة دون كسر التصميم", reduceMotion: "تقليل الحركة", reduceMotionHint: "يوقف الحركات الزخرفية ويحافظ على التغذية الراجعة", directionNotice: "سيُطبق اتجاه اللغة بالكامل عند إعادة فتح التطبيق", preview: "معاينة", sampleTitle: "صيانة واضحة وأسهل للقراءة", sampleBody: "يمكنك تغيير هذه الخيارات في أي وقت" },
  fee: { servicePrice: "سعر الخدمة", platformFee: "رسوم منصة عَمِّرها (10%)", total: "الإجمالي", technicianGets: "يستلم الفني", explanation: "تُضاف رسوم منصة عَمِّرها بنسبة 10% إلى قيمة الخدمة عند إتمام العملية." },
  diagnosis: { title: "التشخيص المبدئي", confidence: "نسبة الثقة: {{value}}%", needsConfirmation: "التشخيص المبدئي يحتاج إلى تأكيد", likelyIssue: "المشكلة المحتملة", serviceType: "نوع الخدمة", technician: "الفني المناسب", urgency: "درجة الاستعجال", duration: "الوقت المتوقع للعمل", disclaimer: "هذا تقييم أولي بمساعدة الذكاء الاصطناعي وليس تشخيصاً مهنياً مضموناً. يؤكد الفني الحالة عند المعاينة.", questionsTitle: "نحتاج تفاصيل سريعة", questionsHint: "إجاباتك تغيّر التشخيص والتوجيه والسعر المتوقع.", refine: "تحديث التشخيص" },
  fairPrice: { title: "السعر العادل المتوقع للخدمة", currency: "شيكل إسرائيلي (NIS)", rangeAccessibility: "من {{min}} إلى {{max}} شيكل", explanation: "التقدير مبني على نوع الخدمة ودرجة الاستعجال، بنسبة ثقة {{confidence}}%.", disclaimer: "هذا تقدير بالذكاء الاصطناعي بناءً على تفاصيل المشكلة المتاحة، وقد تختلف التكلفة النهائية بعد الفحص والقطع المطلوبة وطبيعة العمل الفعلية.", goodValue: "سعر جيد", withinRange: "ضمن النطاق المتوقع", slightlyAbove: "أعلى قليلاً من المتوقع", aboveRange: "أعلى من النطاق المتوقع" },
  routing: { emergencyTitle: "هذه الحالة تحتاج جهة طوارئ", publicTitle: "هذه الحالة تحتاج جهة خدمة عامة", socialTitle: "هذه الحالة تحتاج جهة مساعدة اجتماعية", urgentTitle: "تحتاج فنياً بشكل عاجل", normalTitle: "يمكن متابعة طلب فني", contact: "التواصل مع الجهة المختصة", contactUnavailable: "بيانات الاتصال الموثقة غير مضبوطة حالياً", noAutoContact: "لن يتصل عَمِّرها بأي جهة تلقائياً. أنت من يبدأ الاتصال.", startDispatch: "ابدأ البحث العاجل", expandDispatch: "وسّع نطاق البحث", cancel: "العودة وإلغاء المتابعة" },
  rewards: { title: "مكافآت الشركاء", subtitle: "استبدل نقاطك بعروض وخصومات من شركاء عَمِّرها", balance: "رصيد نقاط عَمِّرها", points: "نقطة", offers: "عروض الشركاء", approved: "الشركاء المعتمدون", empty: "لا توجد مكافآت من الشركاء حالياً.", noHistory: "لا يوجد سجل نقاط بعد.", redeem: "استبدال", insufficient: "نقاط غير كافية", successTitle: "تم الاستبدال بنجاح", successBody: "تمت إضافة القسيمة إلى سجل مكافآتك", notCash: "النقاط مكافآت للاستخدام مع الشركاء وليست رصيداً نقدياً", history: "سجل النقاط والاستبدال", historyEarned: "مكافأة تقييم صيانة موثقة", historyRedeemed: "استبدال قسيمة شريك", earn: "كيف تجمع نقاطاً أكثر؟", earnBody: "أكمل طلب صيانة واكتب تقييماً موثوقاً لتحصل على نقاط إضافية", categories: { electric: "كهرباء", plumbing: "سباكة", building: "مواد بناء", tools: "أدوات" }, catalog: { electric: { partner: "مؤسسة القدس للإنارة", title: "خصم على مستلزمات الكهرباء", description: "واد الجوز • شريك محلي تجريبي", benefit: "خصم 10%" }, plumbing: { partner: "مركز الأقصى للأدوات الصحية", title: "قسيمة أدوات صحية", description: "شعفاط • شريك محلي تجريبي", benefit: "قسيمة 25 ₪" }, stone: { partner: "بيت المقدس لمواد البناء", title: "خصم على مواد البناء", description: "الطور • شريك محلي تجريبي", benefit: "خصم 10%" }, tools: { partner: "أدوات القدس المهنية", title: "عدة صيانة منزلية", description: "باب الزاهرة • شريك محلي تجريبي", benefit: "خصم 20%" } } },
  roles: { logout: "العودة لاختيار الدور" }
} as const;
