export const en = {
  common: { back: "Back", close: "Close", save: "Save", retry: "Try again", loading: "Loading", selected: "Selected" },
  navigation: { home: "Home", requests: "Requests", messages: "Messages", rewards: "Rewards", account: "Account", jobs: "My work", mapRequests: "Map & requests" },
  login: { welcome: "Welcome to AMMERHA", tagline: "Built in Jerusalem, by Jerusalem", choose: "Choose how to enter", noAuth: "This demo does not require a password or account", customer: "Continue as customer", customerHint: "Request repairs and track technicians and offers", technician: "Continue as technician", technicianHint: "View requests, jobs, and messages", admin: "Continue as admin", adminHint: "Monitor verification, safety, and risk", hint: "Choose any role to explore its experience" },
  settings: { title: "Accessibility & appearance", subtitle: "Make AMMERHA work better for you", language: "Language", appearance: "Appearance", accessibility: "Accessibility", arabic: "العربية", english: "English", light: "Light", dark: "Premium dark", highContrast: "High contrast", system: "Use device setting", largeText: "Larger text", largeTextHint: "Enlarges important text without breaking layouts", reduceMotion: "Reduce motion", reduceMotionHint: "Simplifies decorative motion while keeping feedback clear", directionNotice: "Full language direction applies when the app is reopened", preview: "Preview", sampleTitle: "Clearer, easier maintenance", sampleBody: "You can change these options at any time" },
  fee: { servicePrice: "Service price", platformFee: "AMMERHA platform fee (7%)", total: "Total", technicianGets: "Technician receives", explanation: "A 7% AMMERHA platform fee is added to the service price when the transaction is completed." },
  rewards: { title: "Partner Rewards", subtitle: "Redeem your points for offers and discounts from AMMERHA partners", balance: "AMMERHA points balance", points: "points", offers: "Partner offers", approved: "Demo partners", redeem: "Redeem", insufficient: "Not enough points", successTitle: "Reward redeemed", successBody: "The voucher was added to your reward history", notCash: "Points are partner rewards and cannot be withdrawn as cash", history: "Points & redemption history", historyEarned: "Verified service review reward", historyRedeemed: "Partner voucher redeemed", earn: "How to earn more points", earnBody: "Complete a maintenance request and leave a verified review to earn more points", categories: { electric: "Electrical", plumbing: "Plumbing", building: "Building supplies", tools: "Tools" }, catalog: { electric: { partner: "Jerusalem Lighting Co.", title: "Electrical supplies discount", description: "Wadi al-Joz • Demo local partner", benefit: "10% off" }, plumbing: { partner: "Al-Aqsa Plumbing Center", title: "Plumbing supplies voucher", description: "Shuafat • Demo local partner", benefit: "25 ₪ voucher" }, stone: { partner: "Bayt Al-Maqdis Building Supplies", title: "Building supplies discount", description: "At-Tur • Demo local partner", benefit: "10% off" }, tools: { partner: "Jerusalem Professional Tools", title: "Home maintenance tool kit", description: "Herod's Gate • Demo local partner", benefit: "20% off" } } },
  roles: { logout: "Return to role selection" }
} as const;
