import { createAdaptiveStyleSheet } from "../../../shared/theme/adaptiveStyles";
import { Ionicons } from "@expo/vector-icons";
import { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";

import { rewardRepository } from "../../../services/repositories";
import type { Reward, RewardAccount } from "../../../domain/models/reward";
import { LoadingState } from "../../../shared/components";
import { useI18n } from "../../../shared/i18n/I18nProvider";
import { radius, spacing, typography, useTheme } from "../../../shared/theme";

const rewardIcons: Record<string, keyof typeof Ionicons.glyphMap> = { "reward-electric": "flash", "reward-plumbing": "water", "reward-stone": "business", "reward-tools": "hammer" };

export function RewardsScreen() {
  const [account, setAccount] = useState<RewardAccount>();
  const [rewards, setRewards] = useState<readonly Reward[]>([]);
  const { t, isRTL } = useI18n();
  const { theme, textScale, isHighContrast } = useTheme();
  const direction = isRTL ? "row-reverse" : "row";
  const align = isRTL ? "right" : "left";
  useEffect(() => { void Promise.all([rewardRepository.getAccount(), rewardRepository.getRewards()]).then(([nextAccount, nextRewards]) => { setAccount(nextAccount); setRewards(nextRewards); }); }, []);
  if (!account) return <SafeAreaView style={[styles.safe, { backgroundColor: theme.background }]}><LoadingState /></SafeAreaView>;
  const redeem = async (reward: Reward) => { try { setAccount(await rewardRepository.redeem(reward.id)); Alert.alert(t("rewards.successTitle"), t("rewards.successBody")); } catch { Alert.alert(t("rewards.insufficient"), t("rewards.earnBody")); } };
  const size = (value: number) => value * textScale;
  return <SafeAreaView edges={["top"]} style={[styles.safe, { backgroundColor: theme.background }]}>
    <View style={[styles.header, { flexDirection: direction }]}><View style={styles.headerCopy}><Text style={[styles.title, { color: theme.text, fontSize: size(22), textAlign: align }]}>{t("rewards.title")}</Text><Text style={[styles.subtitle, { color: theme.textMuted, fontSize: size(10), textAlign: align }]}>{t("rewards.subtitle")}</Text></View><View style={[styles.headerIcon, { backgroundColor: theme.primarySoft }]}><Ionicons name="star" size={21} color={theme.primaryPressed} /></View></View>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={[styles.balanceCard, { backgroundColor: theme.primary, borderColor: theme.borderStrong, borderWidth: isHighContrast ? 2 : 0 }]}><Ionicons name="sparkles" size={26} color={theme.textInverse} /><Text style={[styles.balanceLabel, { color: theme.textInverse, fontSize: size(11), textAlign: align }]}>{t("rewards.balance")}</Text><View style={[styles.balanceRow, { flexDirection: direction }]}><Text style={[styles.balance, { color: theme.textInverse, fontSize: size(36) }]}>{account.balance}</Text><Text style={[styles.balanceUnit, { color: theme.textInverse, fontSize: size(12) }]}>{t("rewards.points")}</Text></View></View>
      <View style={[styles.notice, { backgroundColor: theme.primarySoft, borderColor: theme.border, flexDirection: direction }]}><Ionicons name="information-circle" size={18} color={theme.primaryPressed} /><Text style={[styles.noticeText, { color: theme.textSecondary, fontSize: size(10), textAlign: align }]}>{t("rewards.notCash")}</Text></View>
      <View style={[styles.sectionHeading, { flexDirection: direction }]}><Text style={[styles.sectionTitle, { color: theme.text, fontSize: size(15), textAlign: align }]}>{t("rewards.offers")}</Text><Text style={[styles.approved, { color: theme.primaryPressed, fontSize: size(9) }]}>{t("rewards.approved")}</Text></View>
      <View style={styles.list}>{rewards.map((reward) => { const canRedeem = account.balance >= reward.pointsCost; return <View key={reward.id} style={[styles.card, { backgroundColor: theme.cardBackground, borderColor: theme.border, borderWidth: isHighContrast ? 2 : 1 }]}>
        <View style={[styles.cardTop, { flexDirection: direction }]}><View style={[styles.rewardIcon, { backgroundColor: theme.primarySoft }]}><Ionicons name={rewardIcons[reward.id] ?? "gift"} size={23} color={theme.primaryPressed} /></View><View style={styles.cardCopy}><View style={[styles.categoryRow, { flexDirection: direction }]}><Text style={[styles.partner, { color: theme.text, fontSize: size(12), textAlign: align }]}>{t(reward.partnerKey)}</Text><Text style={[styles.category, { color: theme.primaryPressed, fontSize: size(8) }]}>{t(reward.categoryKey)}</Text></View><Text style={[styles.rewardTitle, { color: theme.textSecondary, fontSize: size(11), textAlign: align }]}>{t(reward.titleKey)}</Text><Text style={[styles.description, { color: theme.textMuted, fontSize: size(9), textAlign: align }]}>{t(reward.descriptionKey)}</Text></View></View>
        <View style={[styles.footer, { borderTopColor: theme.border, flexDirection: direction }]}><View><Text style={[styles.benefit, { color: theme.success, fontSize: size(11), textAlign: align }]}>{t(reward.benefitKey)}</Text><Text style={[styles.cost, { color: theme.textMuted, fontSize: size(9), textAlign: align }]}>{reward.pointsCost} {t("rewards.points")}</Text></View><Pressable accessibilityRole="button" accessibilityState={{ disabled: !canRedeem }} onPress={() => void redeem(reward)} style={({ pressed }) => [styles.redeem, { backgroundColor: canRedeem ? theme.primary : theme.surfaceSecondary, borderColor: theme.borderStrong, opacity: pressed ? 0.72 : 1 }]}><Text style={[styles.redeemText, { color: canRedeem ? theme.textInverse : theme.textMuted, fontSize: size(10) }]}>{t(canRedeem ? "rewards.redeem" : "rewards.insufficient")}</Text></Pressable></View>
      </View>; })}</View>
      <Text style={[styles.sectionTitle, { color: theme.text, fontSize: size(15), textAlign: align }]}>{t("rewards.history")}</Text>
      <View style={[styles.history, { backgroundColor: theme.cardBackground, borderColor: theme.border }]}>{account.history.map((item) => <View key={item.id} style={[styles.historyRow, { borderBottomColor: theme.border, flexDirection: direction }]}><Text style={[styles.historyLabel, { color: theme.textSecondary, fontSize: size(10), textAlign: align }]}>{t(item.labelKey)}</Text><Text style={[styles.historyPoints, { color: item.points >= 0 ? theme.success : theme.warning, fontSize: size(11) }]}>{item.points > 0 ? "+" : ""}{item.points}</Text></View>)}</View>
      <View style={[styles.earn, { backgroundColor: theme.surfaceSecondary, borderColor: theme.border, flexDirection: direction }]}><Ionicons name="star-outline" size={22} color={theme.primaryPressed} /><View style={styles.earnCopy}><Text style={[styles.earnTitle, { color: theme.text, fontSize: size(11), textAlign: align }]}>{t("rewards.earn")}</Text><Text style={[styles.earnText, { color: theme.textMuted, fontSize: size(9), textAlign: align }]}>{t("rewards.earnBody")}</Text></View></View>
    </ScrollView>
  </SafeAreaView>;
}

const styles = createAdaptiveStyleSheet({ safe: { flex: 1 }, header: { alignItems: "center", justifyContent: "space-between", padding: spacing.md }, headerCopy: { flex: 1 }, title: { fontFamily: typography.fontFamily, fontWeight: "900" }, subtitle: { fontFamily: typography.fontFamily, marginTop: 2 }, headerIcon: { alignItems: "center", borderRadius: 13, height: 42, justifyContent: "center", width: 42 }, content: { padding: 14, paddingBottom: 34 }, balanceCard: { borderRadius: 24, overflow: "hidden", padding: 18 }, balanceLabel: { fontFamily: typography.fontFamily, fontWeight: "700", marginTop: 10 }, balanceRow: { alignItems: "baseline", gap: 7 }, balance: { fontFamily: typography.fontFamily, fontWeight: "900" }, balanceUnit: { fontFamily: typography.fontFamily, fontWeight: "800" }, notice: { alignItems: "center", borderRadius: radius.md, borderWidth: 1, gap: 7, marginTop: 10, padding: 10 }, noticeText: { flex: 1, fontFamily: typography.fontFamily, lineHeight: 16 }, sectionHeading: { alignItems: "center", justifyContent: "space-between", marginBottom: 10, marginTop: 19 }, sectionTitle: { fontFamily: typography.fontFamily, fontWeight: "900", marginBottom: 10, marginTop: 18 }, approved: { fontFamily: typography.fontFamily, fontWeight: "800" }, list: { gap: 10 }, card: { borderRadius: 18, padding: 12 }, cardTop: { alignItems: "center", gap: 10 }, rewardIcon: { alignItems: "center", borderRadius: 13, height: 46, justifyContent: "center", width: 46 }, cardCopy: { flex: 1 }, categoryRow: { alignItems: "center", justifyContent: "space-between" }, partner: { flex: 1, fontFamily: typography.fontFamily, fontWeight: "800" }, category: { fontFamily: typography.fontFamily, fontWeight: "800" }, rewardTitle: { fontFamily: typography.fontFamily, fontWeight: "700", marginTop: 3 }, description: { fontFamily: typography.fontFamily, marginTop: 3 }, footer: { alignItems: "center", borderTopWidth: 1, justifyContent: "space-between", marginTop: 11, paddingTop: 10 }, benefit: { fontFamily: typography.fontFamily, fontWeight: "900" }, cost: { fontFamily: typography.fontFamily, marginTop: 2 }, redeem: { alignItems: "center", borderRadius: 11, borderWidth: 1, justifyContent: "center", minHeight: 40, minWidth: 100, paddingHorizontal: 10 }, redeemText: { fontFamily: typography.fontFamily, fontWeight: "900", textAlign: "center" }, history: { borderRadius: radius.lg, borderWidth: 1, overflow: "hidden" }, historyRow: { alignItems: "center", borderBottomWidth: 1, justifyContent: "space-between", minHeight: 48, paddingHorizontal: 12 }, historyLabel: { flex: 1, fontFamily: typography.fontFamily }, historyPoints: { fontFamily: typography.fontFamily, fontWeight: "900" }, earn: { alignItems: "center", borderRadius: radius.lg, borderWidth: 1, gap: 9, marginTop: 14, padding: 12 }, earnCopy: { flex: 1 }, earnTitle: { fontFamily: typography.fontFamily, fontWeight: "800" }, earnText: { fontFamily: typography.fontFamily, lineHeight: 15, marginTop: 2 } });
